version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - 'MYSQL_ROOT_PASSWORD=KdkR5Z8tybfg2t5r'
      - 'MYSQL_DATABASE=hex_test'
    volumes:
      - ./testdb/:/docker-entrypoint-initdb.d
    ports:
      - '3307:3306'
  hex:
    build: .
    environment:
      - 'DB_DRIVER_NAME=mysql'
      - 'DB_SOURCE_NAME=root:KdkR5Z8tybfg2t5r@tcp(db:3306)/hex_test'
      - 'MYSQL_HOST=db'
      - 'MYSQL_PORT=3306'
      - 'MYSQL_USER=root'
      - 'MYSQL_PASSWORD=KdkR5Z8tybfg2t5r'
      - 'MYSQL_DB=hex_test'
    command: ['go', 'test', '-v', './...']
    depends_on:
      - db
    
